/**
 *  Powered By XROW.ASIA
 *  Real Life Soultions for IT World
 *  Contact: amoswaper@gmail.com
 */
using System.Text;
using XamppMultidomainManager.Models;

namespace XamppMultidomainManager.Services;

public class VirtualHostService
{
    private readonly DatabaseService _dbService;
    private readonly XamppService _xamppService;
    private readonly SslService _sslService;

    private string XamppPath => _xamppService.XamppPath;

    public VirtualHostService(DatabaseService dbService, XamppService xamppService, SslService sslService)
    {
        _dbService = dbService;
        _xamppService = xamppService;
        _sslService = sslService;
    }

    public async Task<(bool Valid, string Message)> RewriteConfig()
    {
        var hosts = _dbService.GetAllHosts().Where(h => h.Enabled).ToList();
        var vhostsPath = Path.Combine(XamppPath, "apache", "conf", "extra", "httpd-vhosts.conf");
        var sslConf = Path.Combine(XamppPath, "apache", "conf", "extra", "httpd-ssl.conf");

        await EnsureVhostIncludeEnabled();
        await EnsureSslEnabled();
        await BlockXamppAliases();

        var httpSB = new StringBuilder();
        httpSB.AppendLine("# Virtual Hosts");
        httpSB.AppendLine("# Auto-generated by XROW.ASIA / XamppMultidomainManager at " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        httpSB.AppendLine();
        httpSB.AppendLine("# XROW.ASIA :: XamppMultidomainManager managed HTTP vhosts - do not edit manually");
        httpSB.AppendLine();

        var sslSB = new StringBuilder();

        foreach (var host in hosts)
        {
            var hasSsl = _sslService.CertificateExists(host.DomainName);
            var root = host.DocumentRoot.Replace('\\', '/');

            EnsureDirectoryExists(root);

            httpSB.AppendLine($"# {host.DomainName}");
            WriteVhostBlock(httpSB, host.DomainName, $"admin@{host.DomainName}", root, host.ServerAlias, false);

            if (hasSsl)
            {
                sslSB.AppendLine($"# {host.DomainName}");
                WriteVhostBlock(sslSB, host.DomainName, $"admin@{host.DomainName}", root, host.ServerAlias, true,
                    _sslService.CertDir.Replace('\\', '/'), _sslService.KeyDir.Replace('\\', '/'));
                sslSB.AppendLine();
            }
        }

        httpSB.AppendLine("# Fallback: localhost serves XAMPP default htdocs");
        WriteVhostBlock(httpSB, "localhost", "admin@localhost",
            Path.Combine(XamppPath, "htdocs").Replace('\\', '/'), null, false);

        try
        {
            var dir = Path.GetDirectoryName(vhostsPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            await File.WriteAllTextAsync(vhostsPath, httpSB.ToString(), Encoding.UTF8);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Failed to write http vhosts config: {ex.Message}");
            return (false, $"Failed to write HTTP vhosts: {ex.Message}");
        }

        try
        {
            await WriteSslVhosts(sslConf, sslSB);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Failed to write ssl vhosts config: {ex.Message}");
            return (false, $"Failed to write SSL vhosts: {ex.Message}");
        }

        // Validate config before returning
        var (valid, msg) = _xamppService.TestConfig();
        return (valid, valid ? "Configuration written successfully" : msg);
    }

    private static void EnsureDirectoryExists(string path)
    {
        try
        {
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            var indexPath = Path.Combine(path, "index.php");
            if (!File.Exists(indexPath))
            {
                var domain = new DirectoryInfo(path).Parent?.Name ?? "site";
                File.WriteAllText(indexPath, $$"""
                    <!DOCTYPE html>
                    <html lang="en">
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <title>{{domain}}</title>
                        <style>
                            * { margin: 0; padding: 0; box-sizing: border-box; }
                            body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0f0f1a; color: #e0e0e0; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
                            .container { text-align: center; padding: 2rem; }
                            h1 { font-size: 3rem; font-weight: 300; margin-bottom: 0.5rem; color: #fff; }
                            h1 span { color: #6c5ce7; }
                            p { color: #888; font-size: 1.1rem; }
                            .domain { margin-top: 2rem; padding: 0.75rem 1.5rem; background: #1a1a2e; border-radius: 12px; display: inline-block; font-size: 0.9rem; color: #6c5ce7; }
                        </style>
                    </head>
                    <body>
                        <div class="container">
                            <h1>Welcome to <span>{{domain}}</span></h1>
                            <p>Your site is ready. Start building.</p>
                            <div class="domain">{{domain}}</div>
                        </div>
                    </body>
                    </html>
                    """);
            }
        }
        catch (Exception ex)
        {
            Logger.Log("VirtualHostService.EnsureDirectoryExists", ex);
        }
    }

    private async Task EnsureVhostIncludeEnabled()
    {
        var httpdConf = Path.Combine(XamppPath, "apache", "conf", "httpd.conf");
        if (!File.Exists(httpdConf)) return;

        var lines = (await File.ReadAllLinesAsync(httpdConf)).ToList();
        var changed = false;
        var found = false;

        for (var i = 0; i < lines.Count; i++)
        {
            var raw = lines[i];
            var trimmed = raw.Trim();

            if (!trimmed.Contains("httpd-vhosts.conf", StringComparison.OrdinalIgnoreCase))
                continue;

            found = true;

            if (trimmed.StartsWith("#", StringComparison.OrdinalIgnoreCase))
            {
                var uncommented = raw.TrimStart().TrimStart('#').TrimStart();
                if (!uncommented.StartsWith("Include", StringComparison.OrdinalIgnoreCase))
                    uncommented = "Include " + uncommented;
                lines[i] = uncommented;
                changed = true;
            }

            break;
        }

        if (!found)
        {
            var insertAt = lines.FindIndex(l =>
                l.Contains("httpd-ssl.conf", StringComparison.OrdinalIgnoreCase));
            if (insertAt < 0)
                insertAt = lines.Count - 1;
            lines.Insert(insertAt, "Include conf/extra/httpd-vhosts.conf");
            changed = true;
        }

        if (changed)
            await File.WriteAllLinesAsync(httpdConf, lines);
    }

    private async Task WriteSslVhosts(string sslConfPath, StringBuilder sslVhosts)
    {
        var lines = (await File.ReadAllLinesAsync(sslConfPath)).ToList();

        const string startMarker = "# XROW.ASIA :: XamppMultidomainManager SSL vhosts START----------";
        const string endMarker = "# XROW.ASIA :: XamppMultidomainManager SSL vhosts END  ----------";

        // Remove existing managed section if present
        var startIdx = lines.FindIndex(l => l.Trim() == startMarker);
        var endIdx = lines.FindIndex(l => l.Trim() == endMarker);
        if (startIdx >= 0 && endIdx > startIdx)
        {
            lines.RemoveRange(startIdx, endIdx - startIdx + 1);
        }

        // Comment out the default _default_:443 vhost block if it's still uncommented
        var defaultVhostStart = -1;
        var defaultVhostEnd = -1;
        var inDefault = false;
        for (var i = 0; i < lines.Count; i++)
        {
            var trimmed = lines[i].Trim();
            if (!inDefault &&
                trimmed.StartsWith("<VirtualHost", StringComparison.OrdinalIgnoreCase) &&
                !trimmed.StartsWith("#") &&
                trimmed.Contains("_default_"))
            {
                inDefault = true;
                defaultVhostStart = i;
                lines[i] = "# " + lines[i];
                continue;
            }

            if (inDefault)
            {
                if (!trimmed.StartsWith("#"))
                    lines[i] = "# " + lines[i];

                if (trimmed == "</VirtualHost>" || trimmed == "# </VirtualHost>")
                {
                    inDefault = false;
                    defaultVhostEnd = i;
                }
            }
        }

        // Find where to insert: after the commented default vhost, or at end
        var insertAt = defaultVhostEnd >= 0 ? defaultVhostEnd + 1 : lines.Count;

        lines.Insert(insertAt++, "");
        lines.Insert(insertAt++, startMarker);
        lines.Insert(insertAt++, "# Powered By XROW.ASIA — Real Life Solutions for IT World");
        foreach (var line in sslVhosts.ToString().Split('\n', StringSplitOptions.None)
            .Select(l => l.TrimEnd('\r')))
        {
            lines.Insert(insertAt++, line);
        }
        lines.Insert(insertAt++, endMarker);

        await File.WriteAllLinesAsync(sslConfPath, lines);
    }

    private async Task BlockXamppAliases()
    {
        var xamppConf = Path.Combine(XamppPath, "apache", "conf", "extra", "httpd-xampp.conf");
        if (!File.Exists(xamppConf)) return;

        var lines = (await File.ReadAllLinesAsync(xamppConf)).ToList();
        var changed = false;

        for (var i = 0; i < lines.Count; i++)
        {
            var trimmed = lines[i].Trim();

            if (!trimmed.StartsWith("Alias", StringComparison.OrdinalIgnoreCase))
                continue;

            if (trimmed.StartsWith("#"))
                continue;

            lines[i] = "# " + lines[i];
            changed = true;
        }

        if (changed)
            await File.WriteAllLinesAsync(xamppConf, lines);
    }

    private async Task EnsureSslEnabled()
    {
        var httpdConf = Path.Combine(XamppPath, "apache", "conf", "httpd.conf");
        if (!File.Exists(httpdConf)) return;

        var lines = (await File.ReadAllLinesAsync(httpdConf)).ToList();
        var changed = false;

        // Remove duplicate Listen 443 if present — httpd-ssl.conf already has it
        for (var i = 0; i < lines.Count; i++)
        {
            var trimmed = lines[i].TrimStart();
            if (trimmed == "Listen 443")
            {
                lines.RemoveAt(i);
                changed = true;
                break;
            }
        }

        if (!lines.Any(l => l.Contains("mod_ssl.so")))
        {
            var idx = lines.FindIndex(l => l.Contains("mod_log_config.so") || l.Contains("mod_alias.so"));
            if (idx >= 0)
            {
                lines.Insert(idx + 1, "LoadModule ssl_module modules/mod_ssl.so");
                changed = true;
            }
        }

        // Ensure httpd-ssl.conf include is uncommented
        var sslInclude = lines.FindIndex(l =>
            l.Trim().Contains("httpd-ssl.conf", StringComparison.OrdinalIgnoreCase));
        if (sslInclude < 0)
        {
            // Add it after the vhosts include
            var vhostsIdx = lines.FindIndex(l =>
                l.Trim().Contains("httpd-vhosts.conf", StringComparison.OrdinalIgnoreCase));
            if (vhostsIdx >= 0)
            {
                lines.Insert(vhostsIdx + 1, "Include conf/extra/httpd-ssl.conf");
                changed = true;
            }
        }
        else
        {
            var raw = lines[sslInclude];
            var trimmed = raw.Trim();
            if (trimmed.StartsWith("#"))
            {
                var uncommented = raw.TrimStart().TrimStart('#').TrimStart();
                if (!uncommented.StartsWith("Include", StringComparison.OrdinalIgnoreCase))
                    uncommented = "Include " + uncommented;
                lines[sslInclude] = uncommented;
                changed = true;
            }
        }

        if (changed)
            await File.WriteAllLinesAsync(httpdConf, lines);
    }

    private static void WriteVhostBlock(StringBuilder sb, string serverName, string serverAdmin,
        string documentRoot, string? serverAlias, bool ssl, string? certDir = null, string? keyDir = null)
    {
        var port = ssl ? 443 : 80;
        sb.AppendLine($"<VirtualHost *:{port}>");
        sb.AppendLine($"    ServerAdmin {serverAdmin}");
        sb.AppendLine($"    DocumentRoot \"{documentRoot}\"");
        sb.AppendLine($"    ServerName {serverName}");

        if (!string.IsNullOrEmpty(serverAlias))
            sb.AppendLine($"    ServerAlias {serverAlias}");

        if (ssl)
        {
            sb.AppendLine("    SSLEngine on");
            sb.AppendLine($"    SSLCertificateFile \"{certDir}/{serverName}.crt\"");
            sb.AppendLine($"    SSLCertificateKeyFile \"{keyDir}/{serverName}.key\"");
        }

        sb.AppendLine("    <Directory \"" + documentRoot + "\">");
        sb.AppendLine("        Options Indexes FollowSymLinks Includes ExecCGI");
        sb.AppendLine("        AllowOverride All");
        sb.AppendLine("        Require all granted");
        sb.AppendLine("    </Directory>");

        sb.AppendLine("</VirtualHost>");
    }

    public async Task RemoveHostFromConfig(string domain)
    {
        var vhostsPath = Path.Combine(XamppPath, "apache", "conf", "extra", "httpd-vhosts.conf");
        if (!File.Exists(vhostsPath)) return;

        var lines = (await File.ReadAllLinesAsync(vhostsPath)).ToList();
        var newLines = new List<string>();
        var skipBlock = false;

        for (int i = 0; i < lines.Count; i++)
        {
            if (lines[i].TrimStart().StartsWith("# ") && lines[i].Contains(domain))
            {
                skipBlock = true;
                continue;
            }

            if (skipBlock)
            {
                if (lines[i].Trim() == "</VirtualHost>")
                {
                    skipBlock = false;
                    continue;
                }
                continue;
            }

            newLines.Add(lines[i]);
        }

        await File.WriteAllLinesAsync(vhostsPath, newLines);
    }
}
